=== ranginui/koha/koha-tmpl/intranet-tmpl/prog/niwa/modules/cataloguing/value_builder/marc21_field_CF.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://koha-community.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://koha-community.org" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
  <xs:annotation>
    <xs:documentation>Control field plugin type of materials schema</xs:documentation>
  </xs:annotation>


  <xs:element name="Tagfield" type="TagfieldType" nillable="false">
    <xs:annotation>
      <xs:documentation>Element indicating the control field</xs:documentation>
    </xs:annotation>
  </xs:element>


  <xs:complexType name="TagfieldType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Material" type="MaterialType"/>
    </xs:sequence>
    <xs:attribute name="tag" type="controltagDataType" use="required"/>
  </xs:complexType>


  <xs:simpleType name="controltagDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="00[1-9A-Za-z]{1}"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="MaterialType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Position" type="PositionType"/>
    </xs:sequence>
    <xs:attribute name="id" type="idDataType" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:simpleType name="idDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:enumeration value="BKS"/>
      <xs:enumeration value="CF"/>
      <xs:enumeration value="MP"/>
      <xs:enumeration value="MU"/>
      <xs:enumeration value="CR"/>
      <xs:enumeration value="VM"/>
      <xs:enumeration value="MX"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="PositionType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Value" type="ValueType"/>
    </xs:sequence>
    <xs:attribute name="pos" type="posDataType" use="required"/>
    <xs:attribute name="url" type="xs:anyURI" use="optional"/>
    <xs:attribute name="urltext" type="xs:string" use="optional"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:simpleType name="posDataType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="[0-9]+(-[0-9]+)?"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:complexType name="ValueType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="description" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== ranginui/koha/koha-tmpl/intranet-tmpl/prog/en-NZ/modules/cataloguing/value_builder/marc21_field_008.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tagfield tag="008" xmlns="http://koha-community.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation= "./marc21_field_CF.xsd">
  <Material id="BKS" name="Books" description="">
    <Position pos="00-05" name="Date entered on file" description=""/>
    <Position pos="06" name="Type of date/ Publication status" description="">
      <Value description="No dates given; B.C. date involved">b</Value>
      <Value description="Continuing resource currently published">c</Value>
      <Value description="Continuing resource ceased publication">d</Value>
      <Value description="Detailed date">e</Value>
      <Value description="Inclusive dates of colletion">i</Value>
      <Value description="Range of years of bulk of collection">k</Value>
      <Value description="Multiple dates">m</Value>
      <Value description="Dates unknown">n</Value>
      <Value description="Date of distribution/ release/ issue and production/ recording session when different">p</Value>
      <Value description="Questionable date">q</Value>
      <Value description="Reprint / reissue date and original date">r</Value>
      <Value description="Single know date / probable date">s</Value>
      <Value description="Publication date and copyright date">t</Value>
      <Value description="Continuings resource status unknown">u</Value>
      <Value description="No attempt to code">|</Value>
    </Position>
    <Position pos="07-10" name="Date 1" description="A date specified by the code in 008/06 (Type of date/ Publication status)">
      <Value description="Date element is not applicable">#</Value>
      <Value description="Date digit">1</Value>
      <Value description="Date digit">2</Value>
      <Value description="Date digit">3</Value>
      <Value description="Date digit">4</Value>
      <Value description="Date digit">5</Value>
      <Value description="Date digit">6</Value>
      <Value description="Date digit">7</Value>
      <Value description="Date digit">8</Value>
      <Value description="Date digit">9</Value>
      <Value description="Date element is totally or partially unknown">u</Value>
      <Value description="No attempt to code">||||</Value>
    </Position>
    <Position pos="11-14" name="Date 2" description="A date specified by the code in 008/06 (Type of date/ Publication status)">
      <Value description="Date element is not applicable">#</Value>
      <Value description="Date digit">1</Value>
      <Value description="Date digit">2</Value>
      <Value description="Date digit">3</Value>
      <Value description="Date digit">4</Value>
      <Value description="Date digit">5</Value>
      <Value description="Date digit">6</Value>
      <Value description="Date digit">7</Value>
      <Value description="Date digit">8</Value>
      <Value description="Date digit">9</Value>
      <Value description="Date element is totally or partially unknown">u</Value>
      <Value description="No attempt to code">||||</Value>
    </Position>
    <Position pos="15-17" url="http://www.loc.gov/marc/countries/countries_code.html" urltext="MARC Code List for Countries" name="Place of publication, production, or execution" description="">
      <Value description="Various places">vp# </Value>
      <Value description="No place, unknown, or undetermined">xx#</Value>
      <Value description="Two-character alphabetic code">[aa#]</Value>
      <Value description="Three-character alphabetic code">[aaa]</Value>
    </Position>
    <Position pos="18-21" name="Illustrations" description="Up to four (4) one-character alphabetic codes (recorded in alphabetical order) that indicate the presence of types of illustrations in the item. If fewer than four alphabetic codes are assigned, the codes are left justified and unused positions contain blanks (#)">
      <Value description="No illustrations">#</Value>
      <Value description="Illustrations">a</Value>
      <Value description="Maps">b</Value>
      <Value description="Portraits">c</Value>
      <Value description="Charts">d</Value>
      <Value description="Plans">e</Value>
      <Value description="Plates">f</Value>
      <Value description="Music">g</Value>
      <Value description="Facsimiles">h</Value>
      <Value description="Coats of arms">i</Value>
      <Value description="Genealogical tables">j</Value>
      <Value description="Forms">k</Value>
      <Value description="Samples">l</Value>
      <Value description="Phonodisc, phonowire, etc">m</Value>
      <Value description="Photographs">o</Value>
      <Value description="Illuminations">p</Value>
      <Value description="No attempt to code">|</Value>
    </Position>
    <Position pos="22" name="Target audience" description="One- character alphabetic code that describes the intellectual level of the target audience for which the material is intended">
      <Value description="Unknown or not specified">#</Value>
      <Value description="Preschool">a</Value>
      <Value description="Primary">b</Value>
      <Value description="Pre-adolescent">c</Value>
      <Value description="Adolescent">d</Value>
      <Value description="Adult">e</Value>
      <Value description="Specialized">f</Value>
      <Value description="General">g</Value>
      <Value description="Juvenile">j</Value>
      <Value description="No attempt to code">|</Value>
    </Position>
    <Position pos="23" name="Form of item" description="One character alphabetic code that specifies the form of material for the item">
      <Value description="None of the following">#</Value>
      <Value description="Microfilm">a</Value>
      <Value description="Microfiche">b</Value>
      <Value description="Microopaque">c</Value>
      <Value description="Large print">d</Value>
      <Value description="Braille">f</Value>
      <Value description="Online">o</Value>
      <Value description="Direct electronic">q</Value>
      <Value description="Regular print reproduction">r</Value>
      <Value description="Electronic">s</Value>
      <Value description="No attempt to code">|</Value>
    </Position>
    <Position pos="24-27" name="Nature of contents" description="Up to four one-character codes that indicate whether a significant part of the item is or contains certain types of material. If fewer than four codes are assigned, the codes are left justified and unused positions contain blanks (#)">
      <Value description="No specified nature of contents">#</Value>
      <Value description="Offprints.Publication that originally was published as an article in a monograph or a serial and that is also issued separately and independently. Includes prepints and postprints">2</Value>
      <Value description="Calendars">5</Value>
      <Value description="Comics/graphic novels">6</Value>
      <Value description="Abstracts/summaries. Abstracts or summaries of other publications. Not used when a publication includes an abstract or summary of its own content.">a</Value>
      <Value description="Bibliographies">b</Value>
      <Value description="Catalogs">c</Value>
      <Value description="Dictionaries. Also used for a glossary or a gazetteer.">d</Value>
      <Value description="Encyclopedias">e</Value>
      <Value description="Handbooks">f</Value>
      <Value description="Legal articles">g</Value>
      <Value description="Indexes. Index to bibliographical material other than itself. Not used when a publication contains an index to its own content.">i</Value>
      <Value description="Patent document">j</Value>
      <Value description="Discographies">k</Value>
      <Value description="Legislation. Full or partial text of enactments of legislative bodies, published either in statute or in code form, or text of rules and regulations issued by executive or adminitrative agencies.">l</Value>
      <Value description="Theses. Thesis, dissertation, or work identified as having been created to satisfy the requirements for an academic certification or degree.">m</Value>
      <Value description="Surveys of literature in a subject area. Composed entirely of authored surveys that summarize what has been published about a subject.">n</Value>
      <Value description="Reviews. Devoted entirely to critical reviews of published or performed works (e.g., books, films, sound recordings, theater)">o</Value>
      <Value description="Programmed texts">p</Value>
      <Value description="Filmographies. Entire item, or a significant part of it, is a filmography or other  bibliografy of moving images.">q</Value>
      <Value description="Directories">r</Value>
      <Value description="Statistics">s</Value>
      <Value description="Technical reports">t</Value>
      <Value description="Standars/specifications">u</Value>
      <Value description="Legal cases and case notes">v</Value>
      <Value description="Law reports and digests">w</Value>
      <Value description="Yearbooks">y</Value>
      <Value description="Treaties. Treaty or accord negotiated between two or more parties to settle a disagreement, establish a relationship, gran rights,etc.">z</Value>
      <Value description="No attempt to code">|</Value>
    </Position>
    <Position pos="28" name="Government publication" description="One-character code that indicates whether or not the item is published or produced by or for an international, national, state, provincial, or local government agency, or by any subdivision of such a body">
      <Value description="Not a government publication">#</Value>
      <Value description="Autonomous or semi-autonomous component">a</Value>
      <Value description="Multilocal">c</Value>
      <Value description="Federal / National">f</Value>
      <Value description="International intergovernmental">i</Value>
      <Value description="Local">l</Value>
      <Value description="Multistate">m</Value>
      <Value description="Government publication-level undetermined">o</Value>
